### ISSUE TITLE
(Rich policy rules) Filtering on the smart contract method call

### ISSUE THREAD

**Issue by leahjaako** [ecadlabs/signatory#59] opened 2019-09-25 19:02 UTC
Ability to specify what methods on the smart contract the operation is invoking

**Comment by AbineshECAD** [comment] 2022-05-26 15:14
Ask Jev whether this is done.

**Comment by jevonearth** [comment] 2022-06-03 14:38
Closing issue, as it is a duplicate of #53

**Closed by jevonearth** 2022-06-03 14:38 UTC
Labels: policy_engine
